apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: backend-config
  namespace: jenkins
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 80
    type: TCP
    requestPath: /