version: '3.9'

services:
  redis:
    image: redis:alpine
  hits:
    image: vhrysh/hit-count:v5
    working_dir: /app
    environment:
      REDIS_HOST: redis
    ports:
      - 80:5000
    volumes:
      - source: ./hits
        target: /app/hits/
        type: bind
    depends_on:
      - redis
