apiVersion: v1
kind: Namespace
metadata:
   name: jenkins
---
apiVersion: v1
kind: Namespace
metadata:
   name: app
---
apiVersion: v1
kind: Namespace
metadata:
   name: prometheus
---
apiVersion: v1
kind: Namespace
metadata:
   name: elk
---
apiVersion: v1
kind: Namespace
metadata:
   name: sonar