apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-logging
  namespace: elk
  labels:
    name: elasticsearch-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elasticsearch-logging
  template:
    metadata:
      labels:
        name: elasticsearch-logging
    spec:
      containers:
        - name: elasticsearch-logging
          image: elasticsearch:7.8.0
          ports:
          - containerPort: 9200
            name: http
          env:
          - name: discovery.type
            value: single-node
