kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  #namespace: kube-system
  namespace: elk
spec:
  selector:
    app: logstash
  #type: NodePort
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044