apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonar-ing
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.static_ip_name }}
spec:
  defaultBackend:
    service:
      name: sonarqube-sv
      port: 
        number: 9000
