---
apiVersion: apps/v1  
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.redis.name }}   
spec:
  selector:
    matchLabels:    
      app: {{ .Values.redis.name }}
  replicas: 
  template:    
    metadata:
      labels:       
        app: {{ .Values.redis.name }}
    spec:            
      containers:
      - name: {{ .Values.redis.name }}
        image: {{ .Values.redis.image }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

---        
apiVersion: v1
kind: Service       
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.namespace }}
  labels:          
    app: {{ .Values.redis.name }}
spec:
  ports:
  - port: 6379     
    targetPort: 6379
  selector:      
    app: {{ .Values.redis.name }}
