apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    name: app-port
  selector:
    app: {{ .Release.Name }}
